name: SERVER distribute

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: themadwolf.kro.kr
          username: ubuntu
          key : ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/project_vue/
            sudo git pull
            sudo yarn
            sudo yarn build
            pm2 reload all
