name: SERVER distribute

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.main.REMOTE_IP }}
          username: ${{ secrets.main.REMOTE_SSH_ID }}
          key : ${{ secrets.main.REMOTE_SSH_KEY }}
          port: ${{ secrets.main.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/project_vue
            sudo git pull
            sudo yarn
            sudo yarn build
            pm2 reload all
