name: SERVER distribute

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: -----BEGIN RSA PRIVATE KEY-----MIIEogIBAAKCAQEAnGS74BlSTEIWGzwlq+0qO0nFI/TXtSsErjfUPra5Tua5Biwzd5URH5dnCU3e6DpVVbTLPrGKmhKhMQ6ljWhwUwQvQPLfbLrUfVIdHJiPH5KTFjY1hsNOa8eL+Sj4cS+Odmbsa5WdCWKRX4MNRTNFd/RY2UEL593zL4+mTffgu1O4Az0j6jjOpX2QjMPWd1upOmtfZwhBcQZpTUMyg1VaEIKQGCAlk3DQ7vbxynKDOnLXCD8wPJmX69s91RPK2B33Idh9JftQ6Kdzo7lDPaiZ1mG9soc9C3qeeFea0lFurRnWL6TA6dyt+QtzhNVf3ll8PyE+yWu+3hFX4LQja6Jc9wIDAQABAoIBAApuj7ehiMNMbzQO3YZr0fLVd2BwHwlXHr9OOwqZ3p98NWBLh31VBKjiTP2qY5GC/pkyb5I1foTLdFQU4YcerctjzpEbAjs69RyM4yM6q+VTvhrvr79W/L6kt1n92SCXpv2P3PpKJwjuubqwv6xbgKlBM8H+HECxpdyIzPOLcsKb9qtoymKDigA5SR/1Xaq0ud0NYpFT3SlLBOipr4dUGeLMyKMz5k3sAeB1YWAFfXJUi5fkChhQG0ARE0M7Q6OMoLGeVvJaHGbm6J+X0s7q/4EdC+4U3Kz8Bwcz51vJ5V7I/Xmi7WQAXT+Ig82xtgmw000qI6Zpn3W8qdXKy6p3W2kCgYEA3FVgk9TiJhj+a0Nfn2xyBau4Bzyv4X4t4E13wsDmjyw3zzoGPIlhifQFkwOrMa/RsPp0pxuQhnqTbYH/GrfsldB000kAJdPzMB+AhULizWrhS9GavjjzBVW/EmcRzpu/H64t5iIBLIiyn8PCjSveFMRAuByKh4dWVR9tFkHGcCkCgYEAtbWui7tkn9ZL01/opMgwQnJfJ96KtXBNcM2DsB4LSNzQxjKLUEOE6Lpkt1OgQpb1Az42o+3t1WC/SdmnGTICV2Cc/bYm1wt96uJVHunUnnjhRevFEZXoMaxk6Fwu9I+XTvZUJ9JxLFsD7E7v4LL1YzSi7jzWGNYufTV8Bb19iB8CgYBn+OoAGL83FyhH2Z0wD+6memf3Ek407GQdqrDO+FRUT5tucIUs3+9lN//BZkPMyJj9GNMfYESNER6s2GFXbF96OspGQfaN4zypAtSVDgEUylDShHCvPxR++f2WY4jlpF1GR91k8br4FvGjrq8KCx9bUVjxCJbeaaD1vkSt8hAAMQKBgCeBIDlwvCejx0hlCYcJnrRTeSyJzU405CEqDP81CO8GUr1EL9V7WGHgZBUXMThI6WuTEv4AtDw3lF7R2uo3XRrx/i+Kclc+QFnYavkVjQwG67Lv1yBDnv9to2KA6BRzQ0n/c7xUnBYwk2HEp5IKVh8DSojQ4Rr1NZYzEouM7sWxAoGARq3JbMxGfr3bb5YRDwUqY/1ojbV2rqU4hvx9n5PEWndmjm6/uvjLq4C/p5IsLlrwk22uEJQRuDUWHWd1ZBrc/Y9lkLyOruC0fkr/jqYadnzVJqYYmjZQCxTAxaOMy5N5cQEVOmUcB3SDikCyCui3K/Pc63ogmGaS7YzObtfy8Ho=-----END RSA PRIVATE KEY-----
          port: 22
          script: |
            cd /home/ubuntu/project_vue
            sudo git pull
            sudo yarn
            sudo yarn build
            pm2 reload all